---

repository:
  name: js-logger
  description: Logger
  homepage: https://github.com/lickdlabs/js-logger
  topics: logger
  private: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
teams:
  - name: lickd
    permission: admin
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
